name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "rune-data-server/gh-actions-cache"

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

      - name: Run test
        run: cargo test --verbose

  build:
    name: Build
    runs-on: 'ubuntu-24.04'
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "rune-data-server/gh-actions-cache"

      - name: Build
        run: |
          cargo build --verbose